app = "trraform-engine"
primary_region = "iad"

[processes]
app = "supercronic /app/crontab"   # single process group called “app”

# No HTTP, so delete the whole [http_service] block
# or keep it with auto_start/stop disabled if you still want 0 → N scaling.

[[vm]]
size = "shared-cpu-1x"

[env]
    LAYER_2_SAMPLE_PER = "10"
    LAYER_1_SAMPLE_PER = "25"
    LINEAR_THRESH = "8"
    SQRT_THRESH = "1000" # switch to ln after this

